[parity]
chain = "/root/.local/share/io.parity.ethereum/chain-spec.json"
base_path = "/root/.local/share/io.parity.ethereum"
[network]
port = 30303
id = 9449
allow_ips = "public"
reserved_peers = "/root/.local/share/io.parity.ethereum/enodes"
[rpc]
port = 8545
apis = ['web3','eth','net','personal','parity','parity_set','traces','rpc','parity_accounts']
